<?xml version="1.0"?>
<package format="2">
  <name>sobits_follower</name>
  <version>0.0.0</version>
  <description>The sobits_follower package</description>

  <maintainer email="sobits@todo.todo">sobits</maintainer>

  <license>TODO</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <!-- Build dependencies -->
  <depend>multiple_sensor_person_tracking</depend>
  <depend>person_following_control</depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>

  <!-- Export build type -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
