/**:
  ros__parameters:
    # Topic & Frame
    scan_topic_name : /sobit_edu/scan
    dr_spaam_topic_name : /dr_spaam_detections
    body_detection_topic_name : /sobit_follower/body_3d_poses
    target_frame : sobit_edu/base_footprint
    odom_frame_name : sobit_edu/odom

    # Tracking
    target_range : 3.0
    leg_tracking_range : 0.40
    body_tracking_range : 0.40
    target_cloud_radius : 0.4
    outlier_radius : 0.1
    outlier_min_pts : 2
    leaf_size : 0.1
    target_change_tolerance : 0.4 #1.0
    # display_marker : true

    # Kalman Filter
    process_noise : 50.0
    system_noise : 1.0
