# Single Shot Multibox Detector
/**:
  ros__parameters:
    # image_topic_name : /rgb_to_depth/image_raw
    # cloud_topic_name : /points2 
    # image_topic_name : /head_rgbd_sensor/rgb/image_rect_color
    # cloud_topic_name : /camera/depth_registered/points
    image_topic_name : /sobit_edu/color/image_raw
    cloud_topic_name : /sobit_edu/depth_registered/points
    # base_frame_name : base_footprint
    base_frame_name : sobit_edu/base_footprint

    image_show_flag : false
    execute_default : true
    ssd_pub_result_image : true
    rqt_image_view_flag : false
    use_tf : false

    ssd_in_scale_factor : 0.007843
    ssd_confidence_threshold : 0.5

    # ssd_prototxt_name : voc_object.prototxt
    # ssd_caffemodel_name : voc_object.caffemodel
    # ssd_class_names_file : voc_object_names.txt

    object_specified_enabled : true
    specified_object_name : person