<?xml version="1.0"?>
<package format="3">
  <name>multiple_observation_kalman_filter</name>
  <version>0.0.0</version>
  <description>The multiple_observation_kalman_filter package</description>

  <maintainer email="sobits@todo.todo">sobits</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
