obstacle_point_topic_name: "/raw_obstacles" # "/obstacles" #
pub_twist_topic_name: "/turtlebot_velocity_smoother/raw_cmd_vel"
robot_position_frame_name: "base_footprint"
odom_frame_name: "odom"
pub_midpoint_marker_topic_name: "/midpoint_marker"
pub_speech_word_topic_name: "/speech_word"
pub_scan_without_target_person_topic_name: "/scan_without_target_person"

max_move_speed: 1.0 # [cm/s] #
back_speed: -0.4 # [cm/s] #
max_trun_speed: 120.0 # [deg/s] #
max_move_distance: 5.0 # [m] #
keep_distance: 0.70 # [m] #
stop_distance: 0.1 # ±[m] #
constant_velocity_distance: 2.0 # [m] #
constant_velocity_deg: 30.0 # [deg] #

distance_from_last_target_point_limit: 0.30 # [m] #




