/**:
  ros__parameters:
    use_rotate : true
    following_position_topic_name : /person
    pan_angle_min_deg : -90.0
    pan_angle_max_deg : 90.0
    tilt_angle_min_deg : 0.0
    tilt_angle_max_deg : 20.0
    camera2person_height : 0.05
    use_smoothing : true
    smoothing_gain : 0.25
    head_pantilt_action_name : /sobit_pro/move_joint
    head_pan_joint_name : head_pan_joint
    head_tilt_joint_name : head_tilt_joint
