<?xml version="1.0"?>
<package format="2">
  <name>person_following_control</name>
  <version>0.0.0</version>
  <description>The person_following_control package</description>

  <maintainer email="sobits@todo.todo">sobits</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nodelet</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>message_filters</depend>
  <depend>nav2_lifecycle_manager</depend>
  <depend>nav2_velocity_smoother</depend>
  <depend>rviz2</depend>
  <depend>qtbase5-dev</depend>
  <depend>multiple_observation_kalman_filter</depend>
  <depend>multiple_sensor_person_tracking</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend> -->

  <!-- <build_depend>qtbase5-dev</build_depend>
  <build_depend>rviz</build_depend>
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-gui</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>
  <exec_depend>rviz</exec_depend> -->

  <!-- The export tag contains other, unspecified, tags -->
    <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
